### ISSUE TITLE
REQUEST: Mac Support

### ISSUE THREAD

**Issue by OllisGit** [MarkTiedemann/todo#1]
Hi Mark,

what about a mac version?

Do you have next week time for a call?

BR
Olli

**Comment by MarkTiedemann** [comment]
Hi @OllisGit, sure! :) I did actually plan to write the same as shell scripts. Unfortunately, `do` is a reserved word in shell, so it'll have to be slightly different. Probably something like `do_`, `did_`, `todo_`, which I have used in the past: [MarkTiedemann/todo_](https://github.com/MarkTiedemann/todo_).

**Comment by MarkTiedemann** [comment]
After further consideration, I think I'd like to develop `todo` for Windows (implemented in Batch) and `todo_` for Mac / Linux (implemented in Shell) as separate projects.

They can, of course, still use the same text file format (e.g. a `todo_list` file which contains the todos and a `todo_counter` file for keeping track of the most recently created todo), and thus, be compatible.

However, I really like how small and simple this project is at the moment so I'd prefer to link to the Shell project from the readme rather than have both in the same repo.

Part of the reason for this decision is that I currently have no plans to sync todos across platforms (as I have done in the past using the `todo_` Rust project mentioned above).

That being said, I'd still like to help build a Shell version. Let's talk next week. :)
